# Generated by Django 4.1.2 on 2022-12-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memberships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('validity', models.PositiveIntegerField()),
                ('desc', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
