# Generated by Django 4.1.2 on 2022-12-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberships',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
