# Generated by Django 4.1.2 on 2022-12-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_memberships_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberships',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
