# Generated by Django 4.1.4 on 2022-12-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_memberships_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberships',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
