# Generated by Django 4.1.4 on 2022-12-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_categories_image_alter_services_image_and_more'),
        ('owner', '0005_alter_memberships_image_alter_memberships_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('status', models.BooleanField(default=True, null=True)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.timeslots')),
            ],
        ),
    ]
