# Generated by Django 4.1.2 on 2022-12-12 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beautician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=150)),
                ('tenure', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='available', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BookedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_slots', models.CharField(max_length=260, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=140, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('validity', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('cost', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.BooleanField(default=True)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('availability', models.IntegerField(blank=True, choices=[('09:00 AM – 09:30 AM', '09:00 AM – 09:30 AM'), ('10:00 AM – 10:30 AM', '10:00 AM – 10:30 AM'), ('11:00 AM – 11:30 AM', '11:00 AM – 11:30 AM'), ('12:00 PM – 12:30 PM', '12:00 PM – 12:30 PM'), ('13:00 PM – 13:30 PM', '13:00 PM – 13:30 PM'), ('14:00 PM – 14:30 PM', '14:00 PM – 14:30 PM'), ('15:00 PM – 15:30 PM', '15:00 PM – 15:30 PM'), ('16:00 PM – 16:30 PM', '16:00 PM – 16:30 PM'), ('17:00 PM – 17:30 PM', '17:00 PM – 17:30 PM')], null=True)),
                ('beautician', models.ManyToManyField(to='customer.beautician')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.categories')),
                ('timeslots', models.ManyToManyField(to='customer.timeslots')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cost', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('booked', 'booked'), ('booking-confirmed', 'booking-confirmed'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='booked', max_length=200)),
                ('beautician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.beautician')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.services')),
                ('timeslot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.bookedslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='beautician',
            name='category',
            field=models.ManyToManyField(blank=True, to='customer.categories'),
        ),
    ]
