# Generated by Django 4.1.4 on 2022-12-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_timeslots_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('pending', 'pending'), ('booked', 'booked')], default='available', max_length=100),
        ),
    ]
