# Generated by Django 4.1.4 on 2022-12-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_categories_image_alter_services_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('validity', models.PositiveIntegerField()),
                ('desc', models.CharField(max_length=300)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('img', models.ImageField(null=True, upload_to='images/')),
                ('status', models.CharField(choices=[('available', 'available'), ('booked', 'booked'), ('not available', 'not available')], default='available', max_length=200)),
            ],
        ),
    ]
